//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.portal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayrollEntities : DbContext
    {
        public PayrollEntities()
            : base("name=PayrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblVIKSATpayEmployee> tblVIKSATpayEmployees { get; set; }
        public DbSet<tblVIKSATUserLoginPart1> tblVIKSATUserLoginPart1 { get; set; }
        public DbSet<tblVIKSATUserLoginPart2> tblVIKSATUserLoginPart2 { get; set; }
        public DbSet<tblVIKSATEmployeeCategory> tblVIKSATEmployeeCategories { get; set; }
        public DbSet<tblVIKSATUserCategory> tblVIKSATUserCategories { get; set; }
        public DbSet<tbUserRoleMaster> tbUserRoleMasters { get; set; }
    }
}
