//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVIKSATEmployeeCategory
    {
        public int fiEmpCategoryId { get; set; }
        public string fvEmpCategoryName { get; set; }
        public string fvEmpCategoryCode { get; set; }
        public Nullable<System.DateTime> fdFromDate { get; set; }
        public Nullable<System.DateTime> fdToDate { get; set; }
        public Nullable<decimal> fnDailyWorkingHours { get; set; }
        public string fvInclusiveWeeklyOffDay { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> Sr { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
