//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVIKSATUserLoginPart1
    {
        public int fiUserId { get; set; }
        public string fvUserName { get; set; }
        public string fvUserPassword { get; set; }
        public Nullable<int> fiCategoryId { get; set; }
        public Nullable<int> fiEmployeeId { get; set; }
        public string fvIsActive { get; set; }
        public string IsTrackingOn { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
