//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVIKSATUserLoginPart2
    {
        public int Id { get; set; }
        public int fiUserId { get; set; }
        public Nullable<int> fiEmpCategoryId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
