//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVIKSATpayEmployee
    {
        public int fiEmployeeID { get; set; }
        public string fvEmployeeCode { get; set; }
        public Nullable<int> fiEmpCategoryId { get; set; }
        public Nullable<int> fiBranchID { get; set; }
        public Nullable<int> fiDepartmentID { get; set; }
        public Nullable<int> fiDesignationID { get; set; }
        public Nullable<int> fiShiftId { get; set; }
        public string fvEmployeeName { get; set; }
        public string fvFatherHusbandName { get; set; }
        public Nullable<System.DateTime> fdDateofBirth { get; set; }
        public string fvAddress1 { get; set; }
        public string fvAddress2 { get; set; }
        public Nullable<int> fiCityId { get; set; }
        public string fvPhone { get; set; }
        public string fvMobile { get; set; }
        public string fvEmail { get; set; }
        public string fvGender { get; set; }
        public string fvBloodGroup { get; set; }
        public string fvIsMarried { get; set; }
        public Nullable<int> fiNoOfChildren { get; set; }
        public Nullable<System.DateTime> fdDateofJoining { get; set; }
        public Nullable<System.DateTime> fdDateofLeft { get; set; }
        public Nullable<System.DateTime> fdDateofTermination { get; set; }
        public string fvPaymentMode { get; set; }
        public Nullable<int> fiBankId { get; set; }
        public string fvBankAccountNo { get; set; }
        public string fvPFNo { get; set; }
        public string fvESINo { get; set; }
        public string fvPANNo { get; set; }
        public string fvLICNo { get; set; }
        public string fvTokenNo { get; set; }
        public string fvPFonBasic { get; set; }
        public string fvPFonMinWages { get; set; }
        public string fvIsActive { get; set; }
        public Nullable<int> fiBoiMatCode { get; set; }
        public string fvDayofWeek { get; set; }
        public string fvAccountHolderName { get; set; }
        public string fvIFSCNO { get; set; }
        public string fvAccountTypeNo { get; set; }
        public string fvAccountHolderAddress { get; set; }
        public string fvEmpBankName { get; set; }
        public string fvResourceID { get; set; }
        public string EmpImage { get; set; }
        public string EmpImagePath { get; set; }
        public string DeviceId { get; set; }
        public string DeviceIMEI { get; set; }
        public string Relation { get; set; }
        public string fvUANNo { get; set; }
        public string IsRegular { get; set; }
        public Nullable<int> ContractorID { get; set; }
        public Nullable<int> MainCategoryID { get; set; }
        public Nullable<int> fiStatus { get; set; }
        public string fvAadhaarNo { get; set; }
        public Nullable<int> fiReportingManager { get; set; }
        public Nullable<int> fiHRManager { get; set; }
        public string fvQualification { get; set; }
        public string fvExperience { get; set; }
        public Nullable<int> fiGradeID { get; set; }
        public string fvReportingManagerName { get; set; }
        public string fvHRManagerName { get; set; }
        public string fvReportIngManagerCode { get; set; }
        public string fvHRManagerCode { get; set; }
        public Nullable<int> fiCostCenterId { get; set; }
        public Nullable<int> fiDivisionID { get; set; }
        public Nullable<int> fiLocationId { get; set; }
        public Nullable<int> fiAccountTypeID { get; set; }
        public Nullable<int> fiPaymentModeId { get; set; }
        public Nullable<int> fiBloodGroupId { get; set; }
    }
}
